apiVersion: v1
kind: Template
metadata:
  name: osiris-observer
  annotations:
    description: >
      This is Osiris Observer Template.
    openshift.io/display-name: 'Thoth: Osiris Observer Template'
    tags: ai-stacks,aistacks,build,build-aggregator,build-analysis,thoth,osiris,osiris-observer
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Osiris Observer Template.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: osiris-observer
    app: osiris
    component: osiris-observer

objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      labels:
        app: osiris
        component: osiris-observer
      name: osiris-observer
    spec:
      name: ${IMAGE_STREAM_TAG}

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      creationTimestamp: null
      labels:
        app: osiris
        component: osiris-observer
      name: osiris-observer
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: osiris-observer:latest
      postCommit: {}
      resources: {}
      source:
        type: Git
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python:latest
            namespace: openshift
      triggers:
        - type: GitHub
          github:
            secret: "osiris-observer-build-trigger"
        - type: ConfigChange
        - type: ImageChange
          automatic: {}

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      creationTimestamp: null
      labels:
        app: osiris
        component: osiris-observer
      name: osiris-observer
    spec:
      replicas: 1
      selector:
        app: osiris
        component: osiris-observer
        deploymentconfig: osiris-observer
        service: osiris-observer
      strategy:
        resources: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: osiris
            component: osiris-observer
            deploymentconfig: osiris-observer
            service: osiris-observer
        spec:
          serviceAccountName: analyzer
          containers:
            - image: osiris-observer:latest
              name: osiris-observer
              resources: {}
              env:
                - name: LOG_LEVEL
                  value: DEBUG
                - name: KUBERNETES_VERIFY_TLS
                  value: '0'
                - name: MIDDLETIER_NAMESPACE
                  value: thoth-test-core
                - name: OSIRIS_HOST_NAME
                  value: ${OSIRIS_HOST_URL}
                - name: OSIRIS_HOST_PORT
                  value: '8000'
                - name: OVERWRITE_EXISTING_LOGS
                  value: '1'

      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            containerNames:
              - osiris-observer
            automatic: true
            from:
              kind: ImageStreamTag
              name: osiris-observer:latest


parameters:
  - description: Name of the github repository for Thoth's Osiris Observer
    displayName: Git Repository
    required: true
    name: GITHUB_URL
    value: 'https://github.com/thoth-station/osiris-build-observer'

  - description: Git reference to be used for Thoth's Osiris Observer
    displayName: Git Reference
    required: true
    name: GITHUB_REF
    value: 'master'

  - description: Tag of the ImageStream to use
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'

  - description: Osiris host url.
    displayName: Osiris host.
    required: true
    name: OSIRIS_HOST_URL
